const supertest = require('supertest');
const app = require('../app');

const api = supertest(app);

test('too long comment', async () => {
	const data = { comment: 'HWDHIUDWQIUHDWQUIHuwueiowqjqweoijqweoijewqoipjqewjej812e29j12e8j289HWDHIUDWQIUHDWQUIHuwueiowqjqweoijqweoijewqoipjqewjej812e29j12e8j289ejweijqweojeqwiojeqoijeioqjiojowvuwefjweiojerwoijwreiojrewoijrwoeipqjwreoiqpjwerqoijrweqoijwerqoipjweqopirjweoirjweqopirjoipwerjoiweqrjopiweqjroiweqjropiweqjroipwqejroiwqejroiweqjroiweqjroiwqejroiweqjropiwqejropiqwejropiweqjroipweqrjoipwqejroiwqejroiewqrjopiwqejropiwqerjHWDHIUDWQIUHDWQUIHuwueiowqjqweoijqweoijewqoipjqewjej812e29j12e8j289ejweijqweojeqwiojeqoijeioqjiojowvuwefjweiojerwoijwreiojrewoijrwoeipqjwreoiqpjwerqoijrweqoijwerqoipjweqopirjweoirjweqopirjoipwerjoiweqrjopiweqjroiweqjropiweqjroipwqejroiwqejroiweqjroiweqjroiwqejroiweqjropiwqejropiqwejropiweqjroipweqrjoipwqejroiwqejroiewqrjopiwqejropiwqerjejweijqweojeqwiojeqoijeioqjiojowvuwefjweiojerwoijwreiojrewoijrwoeipqjwreoiqpjwerqoijrweqoijwerqoipjweqopirjweoirjweqopirjoipwerjoiweqrjopiweqjroiweqjropiweqjroipwqejroiwqejroiweqjroiweqjroiwqejroiweqjropiwqejropiqwejropiweqjroipweqrjoipwqejroiwqejroiewqrjopiwqejropiwqerj' };

	await api
		.post('/api/newcomment/418203094231809123480912348')
		.send(data)
		.expect('Maximum length for comments is 500 characters.');
});
